### ISSUE TITLE
Use TopSky on TC/APP Displays

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#751]
## What is the current situation?
TopSky only used on area profiles

## What is the proposed change?
Approach & TC profiles/displays to use TopSky at the minimum to display part time airspace and danger area activations, other features can be omitted. Tag functionalities such as auto text (on heading assign for example) will therefore be retained.

- [x] Symbols to be disabled (this seems to be the problem, possiblity of using native ES radar track symbols for all)
- [ ] Colours to be changed (see below solution for login callsign based settings)
- [ ] TopSky lines in ASRs require setting up
- [ ] non-TopSky area profiles can have TopSky enabled but retain the tag family

## Reference materials (e.g. screenshots)
![image](https://github.com/VATSIM-UK/uk-controller-pack/assets/13762210/591454d4-ac78-4c24-9f8d-2775041c1b14)
![image](https://github.com/VATSIM-UK/uk-controller-pack/assets/13762210/6c389a45-0f06-4921-b38c-0b0853d9c8e0)

**Comment by luke11brown** [comment]
Instead of another TopSky instance:

Use TopSkySettingsLocal for the following:
EGPH_
(weird colour NOVA)

EGCC_, EGPD etc.
(normal NOVA)

_APP
(NODE)

LTC_, MAN_, STC_
NODE

OCAS areas to have the following added (infills, but retain outline for all):
`ASRDATA:NERC`

NERC ASRs to have the following line added:
`PLUGIN:TopSky plugin:ShowMapData:NERC`

**Comment by luke11brown** [comment]
Run 4 versions of TopSky within the pack?

Automation to check parity of certain file such as TopSkyMaps.txt

```
name: TopSky data match

on: 
  push:
    paths:
      - '/UK/Data/Plugin/TopSky/TopSkyMaps.txt'
      - '/UK/Data/Plugin/TopSky_iTEC/TopSkyMaps.txt'
      - '/UK/Data/Plugin/TopSky_iTEC/TopSkyMaps.txt'

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if files match
        run: |
          if ! cmp --silent file1.txt file2.txt || ! cmp --silent file1.txt file3.txt; then
            echo "TopSKyMaps.txt files do not match!"
            exit 1
          fi
```
        shell: bash
